name: Snowflake Deployment

on:
  push:
    branches:
      - develop
      - QA
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
     FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SnowSQL
        run: |
          pip install snowflake-cli-labs

      - name: Test Snowflake Connection
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT \
                   -u $SNOWFLAKE_USER \
                   -p $SNOWFLAKE_PASSWORD \
                   -w $SNOWFLAKE_WAREHOUSE \
                   -d $SNOWFLAKE_DATABASE \
                   -s $SNOWFLAKE_SCHEMA \
                   -r $SNOWFLAKE_ROLE \
                   -q "SELECT CURRENT_VERSION();"

      - name: Execute SQL Script
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT \
                   -u $SNOWFLAKE_USER \
                   -p $SNOWFLAKE_PASSWORD \
                   -w $SNOWFLAKE_WAREHOUSE \
                   -d $SNOWFLAKE_DATABASE \
                   -s $SNOWFLAKE_SCHEMA \
                   -r $SNOWFLAKE_ROLE \
                   -f scripts/create_tables.sql
