name: Snowflake Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install Snowflake CLI
      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli-labs

      # Verify Snowflake CLI
      - name: Verify Snowflake CLI
        run: |
          snow --version

      # Verify Repository Structure
      - name: Verify Repository Structure
        run: |
          echo "Current Directory:"
          pwd

          echo "Repository Files:"
          ls -R

      # Test Snowflake Connection
      - name: Test Snowflake Connection
        run: |
          snow sql \
            --temporary-connection \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --warehouse $SNOWFLAKE_WAREHOUSE \
            --database $SNOWFLAKE_DATABASE \
            --schema $SNOWFLAKE_SCHEMA \
            --role $SNOWFLAKE_ROLE \
            -q "SELECT CURRENT_VERSION();"

      # Execute Only Changed SQL Files
      - name: Execute Changed SQL Scripts
        run: |

          echo "Checking changed SQL files..."

          files=$(git diff --name-only HEAD~1 HEAD | grep '^scripts/.*\.sql$' || true)

          echo "Changed SQL Files:"
          echo "$files"

          if [ -z "$files" ]; then
            echo "No SQL files changed."
            exit 0
          fi

          for file in $files
          do
            echo "Executing $file"

            snow sql \
              --temporary-connection \
              --account $SNOWFLAKE_ACCOUNT \
              --user $SNOWFLAKE_USER \
              --password $SNOWFLAKE_PASSWORD \
              --warehouse $SNOWFLAKE_WAREHOUSE \
              --database $SNOWFLAKE_DATABASE \
              --schema $SNOWFLAKE_SCHEMA \
              --role $SNOWFLAKE_ROLE \
              -f "$file"

          done

      # Deployment Success Message
      - name: Deployment Completed
        run: |
          echo "Snowflake Deployment Completed Successfully"
