name: Snowflake Deployment

on:
  push:
    branches:
      - develop
      - QA
      - main

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

    steps:

      # Step 1 - Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2 - Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3 - Install Snowflake CLI
      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli-labs

      # Step 4 - Verify Installation
      - name: Verify Snowflake CLI
        run: |
          snow --version

      # Step 5 - Verify Repository Files
      - name: Verify Repository Structure
        run: |
          echo "Current Directory:"
          pwd

          echo "Repository Files:"
          ls -R

      # Step 6 - Test Snowflake Connection
      - name: Test Snowflake Connection
        run: |
          snow sql \
            --temporary-connection \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --warehouse $SNOWFLAKE_WAREHOUSE \
            --database $SNOWFLAKE_DATABASE \
            --schema $SNOWFLAKE_SCHEMA \
            --role $SNOWFLAKE_ROLE \
            -q "SELECT CURRENT_VERSION();"

      # Step 7 - Execute SQL Scripts
      - name: Execute SQL Scripts
        run: |

          echo "Running scripts/create_tables.sql"

          snow sql \
            --temporary-connection \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --warehouse $SNOWFLAKE_WAREHOUSE \
            --database $SNOWFLAKE_DATABASE \
            --schema $SNOWFLAKE_SCHEMA \
            --role $SNOWFLAKE_ROLE \
            -f ./scripts/create_tables.sql

      # Step 8 - Deployment Completed
      - name: Deployment Completed
        run: |
          echo "Snowflake Deployment Completed Successfully"
